### ISSUE TITLE
Help with the web-authentication

### ISSUE THREAD

**Issue by 2waybene** [Clarivate-SAR/wos2vivo#3]
I am very new to wos, python, and web-programming in general. I followed the instruction and installed the wos2vivo.

It seems that I still have the authentication related error:

 File "/ddn/gs1/home/li11/myGit/wos2vivo/wos2vivo/client.py", line 51, in authenticate
    raise Exception("WoS returned 500 error:\n" + rsp.text)
Exception: WoS returned 500 error:
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>No matches returned for Username li11@niehs.nih.gov</faultstring><detail><ns2:AuthenticationException xmlns:ns2="http://auth.cxf.wokmws.thomsonreuters.com"/></detail></soap:Fault></soap:Body></soap:Envelope>

Can anyone help? Thanks.

**Comment by gneissone** [comment]
Hi,
API credentials are not the same as your WoS login credentials. I will contact you directly to determine your API username and password.
